### ISSUE TITLE
Formattage du json

### ISSUE THREAD

**Issue by pachevalier** [cquest/annuaire-services-publics#1]
J'ai essayé de parser le fichier annuaire.sjson mais ça donne des erreurs. Par exemple, [jsonlint](http://jsonlint.com/) renvoie : 

```
Error: Parse error on line 23:
..., Chahr-e Nao"   }} {    "contact_email": 
---------------------^
Expecting 'EOF', '}', ',', ']', got '{'
```

**Comment by cquest** [comment]
Il s'agit de json "streamé", c'est à dire un json par ligne.
